import type { NextPage } from 'next'
import Amplify from 'aws-amplify';
import awsExports from "../src/aws-exports";
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import React from 'react';
// @ts-ignore
import styles from '../styles/Home.module.css'
import { AuthState, onAuthUIStateChange } from '@aws-amplify/ui-components';
import { AmplifyAuthenticator, AmplifySignUp, AmplifySignOut } from '@aws-amplify/ui-react';

Amplify.configure({ ...awsExports, ssr: true });

const App: NextPage = () => {
  const [authState, setAuthState] = React.useState<AuthState>();
  const [user, setUser] = React.useState<object | undefined>();

  React.useEffect(() => {
    return onAuthUIStateChange((nextAuthState, authData) => {
      setAuthState(nextAuthState);
      setUser(authData);
    });
  }, []);

  return authState === AuthState.SignedIn && user ? (
    <div className={styles.container}>
      <Head>
        <title>Todoリスト</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <header className={styles.header}>
        <Link href="/" passHref>
          <h1 className={styles.title}>Todoリスト</h1>
        </Link>
        <AmplifySignOut />
      </header>

      <main className={styles.main}>
        <h2 className={styles.title}>
          ボード一覧は<Link href="/boards" passHref>こちら</Link>
        </h2>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  ) : (
    <AmplifyAuthenticator>
      <AmplifySignUp
        slot="sign-up"
        formFields={[
          { type: "username" },
          { type: "email" },
          { type: "password" }
        ]}
      />
    </AmplifyAuthenticator>
  );
}

export default App