import { Amplify, API, withSSRContext } from 'aws-amplify';
import { GRAPHQL_AUTH_MODE } from '@aws-amplify/api-graphql'
import awsExports from "../..//src/aws-exports";
import type { GetServerSideProps } from 'next'
import { useRouter } from "next/router";
import Head from 'next/head'
import Image from 'next/image'
import React from 'react';
import styles from '../../styles/Home.module.css'
import { listPosts } from "../../src/graphql/queries";
import { createPost } from '../../src/graphql/mutations';
import { Post } from '../../src/API';
import { AuthState, onAuthUIStateChange } from '@aws-amplify/ui-components';
import { AmplifyAuthenticator, AmplifySignUp, AmplifySignOut } from '@aws-amplify/ui-react';

Amplify.configure({ ...awsExports, ssr: true });

export const getServerSideProps: GetServerSideProps = async ({ req }) => {
  const SSR = withSSRContext({ req });
  const response = await SSR.API.graphql({ query: listPosts });

  return {
    props: {
      posts: response.data.listPosts.items,
    },
  };
}

const App = ({ posts = [] }: { posts: Post[] }) => {
  const router = useRouter();
  const { id } = router.query;
  const [authState, setAuthState] = React.useState<AuthState>();
  const [user, setUser] = React.useState<object | undefined>();
  const handleCreatePost = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();

    const form = new FormData(event.currentTarget);

    try {
      const result = await API.graphql({
        authMode: GRAPHQL_AUTH_MODE.AMAZON_COGNITO_USER_POOLS,
        query: createPost,
        variables: {
          input: {
            title: form.get("title"),
            content: form.get("content"),
            status: form.get("status"),
            boardID: id,
            // @ts-ignore
            owner: user.username
          },
        },
      });
      window.location.href = `/boards/${id}`;
    } catch ({ errors }) {
      // @ts-ignore
      console.error(...errors);
      // @ts-ignore
      throw new Error(errors[0].message);
    }
  }

  React.useEffect(() => {
    return onAuthUIStateChange((nextAuthState, authData) => {
      setAuthState(nextAuthState);
      setUser(authData);
    });
  }, []);

  return authState === AuthState.SignedIn && user ? (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <a href="/">
          <h1 className={styles.title}>Todoリスト</h1>
        </a>
        <AmplifySignOut />
      </header>

      <main className={styles.main}>
        <h2 className={styles.title}>
          Todo一覧
        </h2>

        <div className={styles.grid}>
          <div className={styles.card}>
            <h2>新規作成</h2>
            <form onSubmit={handleCreatePost}>
              <fieldset>
                <legend>タイトル</legend>
                <input name="title" />
              </fieldset>
              <fieldset>
                <legend>内容</legend>
                <textarea name="content" />
              </fieldset>
              <fieldset>
                <legend>ステータス</legend>
                <select name="status">
                  <option value="ready">準備中</option>
                  <option value="doing">作業中</option>
                  <option value="done">完了</option>
                  <option value="onHold">保留中</option>
                  <option value="cancelled">キャンセル済み</option>
                </select>
              </fieldset>

              <button>作成</button>
            </form>
          </div>
        </div>

        <div className={styles.grid}>
          {posts.map((post) => (
            <a className={styles.card} href={`/posts/${post.id}`} key={post.id}>
              <h2>{post.title}</h2>
              <p>{post.content}</p>
              <p>ステータス：{post.status}</p>
              <p>作者：{post.owner}</p>
            </a>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  ) : (
    <AmplifyAuthenticator>
      <AmplifySignUp
        slot="sign-up"
        formFields={[
          { type: "username" },
          { type: "email" },
          { type: "password" }
        ]}
      />
    </AmplifyAuthenticator>
  );
}

export default App